pinbook:
  root: "~/pinbook/"
  metadata: "~/pinbook/images/metadata.json"

model:
  weights: "./craft_mlt_25k.pth"
  confidence_threshold: 0.7
  refiner_model: "weights/craft_refiner_CTW1500.pth"

inference:
  low_text: 0.4
  link_threshold: 0.4
  canvas_size: 1280
  mag_ratio: 1.5
  poly: false
  show_time: false
  refine: false
  test_folder: "./images/"

test:
  ground_truths: "~/pinbook/ground_truths/ground_truths.csv"

results:
  root: "~/pinbook/results/"
  craft: "~/pinbook/results/craft_results/"
  yolo: "~/pinbook/results/yolo_results/"

